steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_JOB_NAME:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '$_JOB_NAME:$TAG_NAME', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_JOB_NAME/$_JOB_NAME:$TAG_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_JOB_NAME/$_JOB_NAME:$TAG_NAME']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  env:
    - HOST=$_REGION-docker.pkg.dev
    - PROJECT=$PROJECT_ID
    - REPO=$_JOB_NAME
    - SERVICE=$_JOB_NAME
    - COMMIT=$TAG_NAME
    - REGION=$_REGION
  script: |
    #!/usr/bin/env bash
    jobs=$(gcloud run jobs list --format="value(name)")
    echo jobs
    for job in $jobs; do
      if [[ $job == "parking-lot-allavailable"* ]]; then
        gcloud run jobs update $job --image=$HOST/$PROJECT/$REPO/$SERVICE:$COMMIT --region=REGION
      fi
    done
images:
- '$_REGION-docker.pkg.dev/$PROJECT_ID/$_JOB_NAME/$_JOB_NAME:$TAG_NAME'